-- MySQL Script generated by MySQL Workbench
-- Thu May 28 01:48:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jugueteriamodelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jugueteriaTOP` DEFAULT CHARACTER SET utf8 ;
USE `jugueteriaTOP` ;

CREATE TABLE IF NOT EXISTS `personas` (
  `IdPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(75) NOT NULL,
  `Apellido1` VARCHAR(75) NOT NULL,
  `Apellido2` VARCHAR(75) NULL,
  `DNI` VARCHAR(9) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`IdPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `tareas` (
  `IdTarea` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `personas_IdPersona` INT NOT NULL,
  `IdJuguete` INT NOT NULL,
  PRIMARY KEY (`IdTarea`),
  INDEX `fk_category_personas_idx` (`personas_IdPersona` ASC) VISIBLE,
  CONSTRAINT `fk_category_personas`
    FOREIGN KEY (`personas_IdPersona`)
    REFERENCES `personas` (`IdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `jugueteriamodelo` ;

-- -----------------------------------------------------
-- Table `jugueteriamodelo`.`juguete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juguete` (
  `IdJuguete` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `IdPersona` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`IdJuguete`),
  INDEX `FK_Publicacion_Persona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `FK_Publicacion_Persona`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `personas` (`IdPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jugueteriamodelo`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `material` (
  `IdMaterial` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Cantidad` INT NOT NULL,
  `juguete_IdJuguete` INT NOT NULL,
  PRIMARY KEY (`IdMaterial`),
  INDEX `fk_material_juguete1_idx` (`juguete_IdJuguete` ASC) VISIBLE,
  CONSTRAINT `fk_material_juguete1`
    FOREIGN KEY (`juguete_IdJuguete`)
    REFERENCES `juguete` (`IdJuguete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jugueteriamodelo`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `IdRol` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario` CHAR(1) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jugueteriamodelo`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menus` (
  `IdMenu` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Tipo` ENUM('S', 'I') NOT NULL,
  `Estado` BIT(1) NOT NULL DEFAULT b'1',
  `IdRol` INT NOT NULL,
  `IdMenu_Menu` INT NULL DEFAULT NULL,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMenu`),
  INDEX `FK_Menu_Rol` (`IdRol` ASC) VISIBLE,
  INDEX `Fk_Menu_menu` (`IdMenu_Menu` ASC) VISIBLE,
  CONSTRAINT `Fk_Menu_menu`
    FOREIGN KEY (`IdMenu_Menu`)
    REFERENCES `menus` (`IdMenu`),
  CONSTRAINT `FK_Menu_Rol`
    FOREIGN KEY (`IdRol`)
    REFERENCES `roles` (`IdRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jugueteriamodelo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `UltimaConexion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Estado` BIT(1) NOT NULL,
  `IdPersona` INT NOT NULL,
  `IdRol` INT NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `FK_Usuario_Persona` (`IdPersona` ASC) VISIBLE,
  INDEX `FK_Usuario_Rol` (`IdRol` ASC) VISIBLE,
  CONSTRAINT `FK_Usuario_Persona`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `personas` (`IdPersona`),
  CONSTRAINT `FK_Usuario_Rol`
    FOREIGN KEY (`IdRol`)
    REFERENCES `roles` (`IdRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
